name: Deploy

on: [push, pull_request]
  
jobs:
  deploy:    
    runs-on: ubuntu-latest 

    steps:
    - name: pulling git repo
      uses: actions/checkout@v2
    - name: deploying to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 94938ad0-d8fc-432a-a3d6-4f2aa3d6693d
        heroku_app_name: youtube-dev-f
        heroku_email: ytbdev10@gmail.com
